name: CI Pipeline with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Авторизуемся в GHCR (если используешь GitHub Container Registry)
      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      # Шаг 3: Запускаем тесты в Docker-контейнере
      - name: Run tests in Docker
        run: |
          docker run --rm \
            -v "$(pwd)/test_results:/app/test_results" \
            ghcr.io/${{ github.actor }}/my-test-image:latest

      # Шаг 4: Генерируем Allure-отчет
      - name: Generate Allure report
        run: |
          allure generate test_results --output allure-report --clean
