name: CI Pipeline with Allure

on:
  push:
    branches:
      - main  # Запускать пайплайн при пуше в main
  pull_request:
    branches:
      - main  # Запускать пайплайн при создании PR в main

jobs:
  test:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Укажи нужную версию Python

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Установи зависимости из файла

      # Шаг 4: Запускаем тесты и генерируем сырые данные Allure
      - name: Run tests with Allure
        run: |
          pytest --alluredir=test_results

      # Шаг 5: Генерируем Allure-отчет
      - name: Generate Allure report
        run: |
          allure serve test_results

      # Шаг 6: Сохраняем сырые данные Allure как артефакты
      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: test_results