name: CI Pipeline with Allure

on:
  push:
    branches:
      - main  # Запускать пайплайн при пуше в main
  pull_request:
    branches:
      - main  # Запускать пайплайн при создании PR в main

jobs:
  test:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Укажи нужную версию Python

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Установи зависимости из файла

      # Шаг 4: Устанавливаем Allure CLI
      - name: Install Allure CLI
        run: |
          # Скачиваем Allure CLI
          sudo apt-get update
          sudo apt-get install wget unzip
          wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.zip
          sudo unzip allure-2.24.0.zip -d /opt/
          sudo ln -s /opt/allure-2.24.0/bin/allure /usr/bin/allure
          allure --version

      # Шаг 5: Запускаем тесты и генерируем сырые данные Allure
      - name: Run tests with Allure
        run: |
          pytest --alluredir=test_results
        
      # Шаг 6: Генерируем Allure-отчет
      - name: Generate Allure report
        run: |
          allure generate test_results --output allure-report

      # Шаг 7: Сохраняем сырые данные Allure как артефакты
      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      # # Шаг 6: Генерируем Allure-отчет
      # - name: Generate Allure report
      #   run: |
      #     allure serve test_results

      # # Шаг 7: Сохраняем сырые данные Allure как артефакты
      # - name: Upload Allure results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: allure-results
      #     path: test_results